### ISSUE TITLE
Unable to login user 'null'

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/MetPlus_resumeCruncher#68]
Got everything set up - mongodb running fine, but when we do a post we get a 401 and the following errors in the log:

```
2018-11-23 13:50:52.337  INFO 35710 --- [nio-8443-exec-3] o.m.c.security.useCases.UserTryToLogin   : Unable to login user 'null'
2018-11-23 13:50:52.343  INFO 35710 --- [nio-8443-exec-3] o.m.c.s.filters.ApplicationLoginFilter   : Invalid credentials on request from '0:0:0:0:0:0:0:1'
```

**Comment by joaopapereira** [comment]
Yeah, take a look in [here](http://joaopapereira.github.io/MetPlus_resumeCruncher/)
This is the documentation for the HTTP.

The flow is as follows:
1. Authenticate the user to get a token
2. Use the token to perform operation


1. The request to get authenticated looks like this:
```
POST /api/v1/authenticate HTTP/1.1
Accept: application/json
X-Auth-Username: backend_admin
X-Auth-Password: backendpassword
Host: localhost:8080
```
The 2 headers that you see there are needed to login
The reply will be:
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 49

{"token": "aa777f45-4b6c-4bc4-b67d-b6829e8fece4"}
```

2. Now you have the token that you need to do the other operation. The token need to go in the header: `X-Auth-Token`

From the error that you pasted there are 2 options:
1. You didn't authenticate and are trying to perform operations without token
2. You are trying to authenticate but the required headers are not present as you can see in the error message `Unable to login user 'null'`

**Comment by tansaku** [comment]
thanks @joaopereira - thought we did do all that stuff - we are posting to try and get that token ... will double check all the headers I guess

**Comment by tansaku** [comment]
@joaopapereira I've double checked - we are just trying to get a token - see this:

![](https://dl.dropbox.com/s/7s6vyh0iwuijzal/Screenshot%202018-11-23%2017.14.15.png?dl=0)

**Comment by tansaku** [comment]
and it gives 401 Unauthorized just trying to get the token in the first place - we get `Unable to login user 'null'` in the log

**Comment by joaopapereira** [comment]
@tansaku you need to set `X-Auth-Username` and `X-Auth-Password` as Headers for the request, not parameters

**Comment by joaopapereira** [comment]
Cool are you ok if we close it?
